select * from developer;
select * from jiratask;

INSERT INTO JIRATASK(TASK_ID,TASK_NAME, STATUS, DUEDATE, BLOCKER) VALUES (101,'Main Page Design', 'In Progress', '2018-08-10',TRUE);
INSERT INTO JIRATASK(TASK_ID,TASK_NAME, STATUS, DUEDATE, BLOCKER) VALUES (102,'Provide Testing Data','In UAT','2018-08-10', FALSE);
INSERT INTO JIRATASK( TASK_ID,TASK_NAME, STATUS, DUEDATE, BLOCKER) VALUES (103,'Rest Service','In QA', '2018-08-10',TRUE);
INSERT INTO JIRATASK( TASK_ID,TASK_NAME, STATUS, DUEDATE, BLOCKER) VALUES (104,'Create New Tables','DONE','2018-08-10', FALSE);
INSERT INTO JIRATASK( TASK_ID,TASK_NAME, STATUS, DUEDATE, BLOCKER) VALUES (105,'Bug fix on Main Page','DONE','2018-08-10', FALSE);

INSERT INTO DEVELOPER (DEVELOPER_ID,TASK_ID,FIRST_NAME, LAST_NAME, TEAM_NAME) VALUES (201,101,'John', 'Hawkins', 'Front-End team');
INSERT INTO DEVELOPER (DEVELOPER_ID,TASK_ID,FIRST_NAME, LAST_NAME, TEAM_NAME) VALUES (202,102,'Mary', 'Woods', 'Data Team');
INSERT INTO DEVELOPER (DEVELOPER_ID,TASK_ID,FIRST_NAME, LAST_NAME, TEAM_NAME) VALUES (203,103,'Sarah', 'Phillips', 'Back-End Team ');
INSERT INTO DEVELOPER (DEVELOPER_ID,TASK_ID,FIRST_NAME, LAST_NAME, TEAM_NAME) VALUES (204,104,'Mark', 'Mayfield', 'Database Team');
INSERT INTO DEVELOPER (DEVELOPER_ID,TASK_ID,FIRST_NAME, LAST_NAME, TEAM_NAME) VALUES (205,105,'Ryan', 'McCullough', 'Front-End Team');

