CREATE TABLE JIRATASK(
  TASK_ID INTEGER  PRIMARY KEY,
  TASK_NAME VARCHAR(2048),
  STATUS VARCHAR(50) NOT NULL,
  DUEDATE DATE NOT NULL,
  BLOCKER BOOLEAN
);

CREATE TABLE DEVELOPER(
  DEVELOPER_ID INTEGER PRIMARY KEY,
  TASK_ID INTEGER NOT NULL,
  FIRST_NAME VARCHAR(32) NOT NULL,
  LAST_NAME VARCHAR(32) NOT NULL,
  TEAM_NAME VARCHAR(128) NOT NULL,
  FOREIGN KEY (TASK_ID) REFERENCES JIRATASK(TASK_ID)  
);
